services:
  db:
    image: postgres:16
    container_name: w2w-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: movies
    volumes:
      - movies-data:/var/lib/postgresql/data

volumes:
  movies-data:
